name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - wiki

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: LS
        run: ls -al

      - name: PWD
        run: pwd

      # Step to create CNAME file for redirection
      - name: Create CNAME file
        run: echo "yourcustomdomain.com" > ./build/CNAME

      # Popular action to deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
